--
- name: Configure firewall rules for nginx and apache
  gather_facts: false
  become: true
  hosts: apps
  
  tasks:
    - name: Setup user ssh key on jump host
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', '/home/thor/.ssh/id_rsa.pub') }}"

    # Ensure packages are installed
    - name: Check and install nginx package
      yum:
        name: "nginx"
        state: installed

    - name: Check and install httpd package
      yum:
        name: "httpd"
        state: installed

    - name: Check and install firewalld package
      yum:
        name: "firewalld"
        state: installed

    - name: start dbus 
      service:
        name: dbus
        state: restarted
        enabled: yes

    - name: start firewalld 
      service: 
        name: firewalld 
        state: restarted
        enabled: yes

    - name: enable rich rule
      firewalld:
        ## change port ##
        rich_rule: rule family=ipv4 protocol=tcp to-port=8443 accept
	source: 172.16.238.12
        permanent: yes
        state: enabled

    - name: start firewalld 
      service:
        name: firewalld
        state: restarted
        enabled: yes

    - name: enabe httpd service rule 
      firewalld:
	zone: public
        rich_rule: rule service name="http" accept
        permanent: yes
        state: enabled

    - name: start httpd 
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: start nginx 
      service:
        name: nginx
        state: restarted
        enabled: yes



