---
- name: Configure firewall rules for nginx and apache
  gather_facts: false
  become: true
  hosts: apps

  tasks:
    - name: Setup user ssh key on jump host
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', '/home/thor/.ssh/id_rsa.pub') }}"

    # Ensure packages are installed
    - name: Check and install nginx package
      yum:
        name: "nginx"
        state: installed

    - name: Check and install httpd package
      yum:
        name: "httpd"
        state: installed

    - name: Check and install firewalld package
      yum:
        name: "firewalld"
        state: installed

    - name: start dbus
      service:
        name: dbus
        state: restarted
        enabled: yes

    - name: start firewalld
      service:
        name: firewalld
        state: restarted
        enabled: yes

    - name: enable rich rule
      firewalld:
        rich_rule: family="ipv4" source address="172.16.238.14" port port=8082 protocol=tcp accept
        permanent: yes
        state: enabled

    - name: enabe httpd service rule
      firewalld:
        rich_rule: family="ipv4" source address=* port port=8096 protocol=tcp accept
        zone: public
        permanent: yes
        state: enabled

    - name: start firewalld
      service:
        name: firewalld
        state: restarted
        enabled: yes

    - name: start httpd
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: start nginx
      service:
        name: nginx
        state: restarted
        enabled: yes

