---
- hosts: db
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: install postgresql server and client
      yum: 
        name:  
          - postgresql-server
          - postgresql
          - postgresql-plpython
          - PyGreSQL
          - python-psycopg2
          - python-ipaddress
        state: present
        
    #- name: python pip psycopg2
    #  shell: | 
    #     pip install python-psycopg2 
    #  ignore_errors: yes
      
    - name: initalize postgresql-server
      shell: | 
         /usr/bin/postgresql-setup initdb
      ignore_errors: yes
 
    #- name: copy /usr/share/pgsql/postgresql.conf.sample
    #  copy: 
    #    src: /usr/share/pgsql/postgresql.com.sample
    #    dest: /var/lib/pgsql/data/postgresql.conf
    #    remote_src: yes
         
    - name: Update postgresql listen value
      lineinfile: 
        dest: /var/lib/pgsql/data/postgresql.conf
        backup: yes
        regexp: "^listen_addresses"
        line: "listen_addresses  = '*'"
        state: present

    - name: update pg_hba.conf
      postgresql_pg_hba:
        dest: /var/lib/pgsql/data/pg_hba.conf
        contype: host
        users: "{{ db_user }}"
        source: 172.16.238.0/24
        databases: "{{ db_name }}"
    
    - name: start postgresql server
      service: 
        name: postgresql
        state: started

    - name: Create database user 
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_passwd }}"
        priv: '*.*:ALL' 
        state: present

    - name: Create a new database 
      postgresql_db:
        name: "{{ db_name }}"
        state: present
  
    - name: Setup privs for created db
      postgresql_privs:
        db: "{{ db_name }}"
        privs: ALL
        roles: librarian,reader
        grant_option: yes

- hosts: apps
  become: true
  
  vars_files:
    - vars.yml
    
  tasks:
    - name: install postgresql server and client
      yum: 
        name:  
          - postgresql
        state: present

