---
- hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: install mariadb-server and mariadb
      yum: 
        name:  
          - mariadb-server
          - mariadb
        state: present
    
    - name: Create database user 
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_passwd }}"
        priv: '*.*:ALL' 
        state: present

    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: "{{ db_name }}"
        state: present
   
    - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
      mysql_db:
        state: import
        name: "{{ db_name }}"
        target: "{{ db_dumpfile }}" 

