---
- hosts: db
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: install mariadb-server and mariadb
      yum: 
        name:  
          - mariadb-server
          - mariadb
        state: present
    
    - name: Create database user 
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_passwd }}"
        priv: '*.*:ALL' 
        state: present

    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: "{{ db_name }}"
        state: present
   
    - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
      mysql_db:
        state: import
        name: "{{ db_name }}"
        target: "{{ db_dumpfile }}" 

- hosts: storage
  become: true
  
  vars_files:
    - wpvars.yml
    
  tasks:
    - name: Update WordPress config.php variable for DB user setting
      lineinfile: 
        dest: /data/wp-config.php
        backup: yes
        regexp: "fix these RNAME }}\\s+ALL=\\(ALL\\)\\s*ALL" 
        line: "{{ ATMOUSERNAME }} ALL=(ALL) ALL" 
        state: present

    - name: Update WordPress config.php variable for DB password setting
      lineinfile: 
        dest: /data/wp-config.php
        backup: no
        regexp: "fix these}}\\s+ALL=\\(ALL\\)\\s*ALL" 
        line: "{{ ATMOUSERNAME }} ALL=(ALL) ALL" 
        state: present

    - name: Update WordPress config.php variable for DB server setting
      lineinfile: 
        dest: /data/wp-config.php
        backup: yes
        regexp: "dbhost" 
        line: "{{ DBHOSTNAME }}" 
        state: present
        
        

        
 

